### PR TITLE
Respect `configureWebpack` option in vue.config.js

### LINKED ISSUE #37: vue-cli webpack config not fully copied ?
Hi.

in vue.config.js I've among other stuff:
```
performance: { hints: false },
resolve: { alias: { '~': path.resolve(__dirname) } },
```
**It seems none of those are copied in the configuration for Storybook** because 1) I get the performance messages and 2) I get errors like `Module not found: Error: Can't resolve '~/config' in ...`

If I create a Storybook's webpack.config.js and add those properties than it's working fine.

_@vue/cli-service 3.1.1_
_vue-cli-plugin-storybook 0.4.8_

### PR DESCRIPTION
**Pull request by jimvandervoort**
Storybook currently does not pickup on config defined in `configureWebpack:`, only chained config defined through the chain-loader option. This PR changes that behaviour and uses `api.resolveWebpackConfig()` (which includes both config defined through both options in vue.config.js).

This makes it easier to work with storybook for users that define e.g aliases without using chain-loader.

Plugins are still filtered through chain-loader only because plain webpack config does not allow us to easily name plugins.

This closes #37

### CODE REVIEW

File: preset.js [hunk 1]
```diff
@@ -13,27 +13,28 @@ module.exports = {
...
     });
 
-    const resolvedConfig = chain.toConfig();
+    const resolvedChain = chainConfig.toConfig();
+    const webpackConfig = api.resolveWebpackConfig();
 
     return {
       ...config,
-      plugins: [...config.plugins, ...resolvedConfig.plugins],
+      plugins: [...config.plugins, ...resolvedChain.plugins],
```
Comment (pksunkara) [inline preset.js]: I don't like this part. We have to have only one final resolved config. We have two here. If you see [here](https://github.com/vuejs/vue-cli/blob/047872c25eee9f70b5e9e2a67eded2714556e2a7/packages/%40vue/cli-service/lib/Service.js#L229), `resolveWebpackConfig()` does include the chained webpack config. So, my thought is to change the above `resolvedConfig = api.resolveWebpackConfig(resolvedChain)` and use the `resolvedConfig` here. You get what I am saying?

File: preset.js [hunk 2]
```diff
@@ -1,7 +1,7 @@
 module.exports = {
   webpack: (config, { api, options }) => {
-    const chain = api.resolveChainableWebpackConfig();
-    const existingPlugins = chain.plugins.values().map(item => item.name);
+    const chainConfig = api.resolveChainableWebpackConfig();
```
Comment (pksunkara) [inline preset.js]: Is the variable renamed for readability?

File: preset.js (hunk 1 above)
Comment (jimvandervoort) [reply preset.js]: I agree we need only one config here. However, the current filter method uses the names from webpack-chain. I don't think we want to filter the config from `resolveWebpackConfig()` since we could only filter by checking if any defined plugin is an instance of a certain plugin class which would mean we could either have no instances of a plugin or all of them. Currently we can filter based on the name we gave the plugin instance with chain-webpack.

The most basic solution would be to only allow plugins defined through chainWebpack.

The most 'complete' option would be to allow both classes and webpack-chain string names to be filtered, but then we'll still need to resolve both configs.

Another options would be to reconsider this feature, what is the reason this filter options was implemented? Is storybook incompatible with standard vue-cli plugins? Otherwise we might create a blacklist or instruct the user not to install certain plugins when building for storybook.

What do you thinks is best?

Comment (jimvandervoort) [reply preset.js]: Goo call, pushed.

**Comment by jimvandervoort** [comment]
> Great work! But I would suggest a few changes. let me know what you think. Do you think you can also write a test? Don't mind if you can't get the tests to work.

Always a fan of testing! I'm not sure how to add a test to the current setup (not very familiar with chromatic), since it seems to me I would need to get the script to fail if a certain webpack config is not read, but that would mean changing the generator in a way no users could use it out of the box.

Shall I add some unit tests instead?

File: README.md [hunk 3]
```diff
@@ -28,6 +28,8 @@ However, storybook will filter all the plugins for webpack according to internal
 }
 ```
 
+Note that only plugins defined with [webpack-chain](https://cli.vuejs.org/guide/webpack.html#chaining-advanced) config can be used in storybook.
```
Comment (pksunkara) [inline README.md]: We need to revisit this. I don't think this line is valid anymore.

**Comment by pksunkara** [comment]
If you need to test this, we need to change (using script) the vue config of the generated test project which uses `configureWebpack` (adding the alias like in the issue). And then we need to somehow use the alias (using script to change the project). This would fail before this PR because storybook would error out.

If it's too complex, you can leave it. Just one comment to fix and I can merge the PR.

File: README.md (hunk 3 above)
Comment (jimvandervoort) [reply README.md]: Right, pushed

**Comment by jimvandervoort** [comment]
I left a comment for the tests aliases with the generator without breaking the generator for users.
